### ISSUE TITLE
关于fabric-sdk-java Install chaincode的问题

### ISSUE THREAD

**Issue by HeartWillGo** [DAYUCS/Hyperledger#1]
你好，我最近在做HyperLedger fabric相关的项目，项目中遇到些问题。
我在Install chaincode的时候，response返回是成功的，但Instantiate chain code.的时候会出错。
我查看了一下原因，发现他Instantiate的时候一直默认的是官方给的代码，无法Instantiate自己的 chain code
不知道您有没有遇到过此类问题。
项目正在开发中，为这个问题已经停留好多天了，求助一下。
联系我Email：heartgo1996@163.com

**Comment by DAYUCS** [comment]
非本项目的问题。
